[ 2024-12-31 22:15:36,231 ] 12 root - INFO - Starting data ingestion...
[ 2024-12-31 22:15:39,538 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2024-12-31 22:15:39,539 ] 16 root - INFO - Starting data preprocessing...
[ 2024-12-31 22:15:39,591 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2024-12-31 22:15:39,591 ] 20 root - INFO - Starting model training...
[ 2024-12-31 22:15:39,592 ] 53 root - ERROR - An error occurred during model training: [Errno 13] Permission denied: 'D:/My projects/Medical Insurane Predictor/data\\Processed_data'
[ 2024-12-31 22:15:39,592 ] 16 root - ERROR - Custom Exception: Error occurred in script [D:\My projects\Medical Insurane Predictor\src\mlProject\components\model_trainer.py] line number [19] error message [[Errno 13] Permission denied: 'D:/My projects/Medical Insurane Predictor/data\\Processed_data']
[ 2024-12-31 22:15:39,592 ] 25 root - ERROR - Custom error occurred: Error occurred in script [D:\My projects\Medical Insurane Predictor\src\mlProject\components\model_trainer.py] line number [19] error message [[Errno 13] Permission denied: 'D:/My projects/Medical Insurane Predictor/data\\Processed_data']
